#print("Hello world")
print("Rahul Rao Nilapu")
print("Mrs White")
print("Kings High School")
print("5")
print("2047")
print("2122")
print("94")
print("53")
print("Tekken 7")
print("Digital Technology")